# Generated by Django 3.0 on 2021-04-02 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rating'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_getter', to='profiles.Profile'),
        ),
    ]
