# Generated by Django 3.0 on 2021-03-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='work_area',
        ),
        migrations.AddField(
            model_name='job',
            name='budget',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
