# Generated by Django 3.0 on 2021-03-23 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('posts', '0002_auto_20210324_0146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='budget',
            new_name='salary',
        ),
        migrations.AddField(
            model_name='job',
            name='work_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_work_area', to='profiles.Area'),
        ),
    ]
