# Generated by Django 3.0 on 2021-04-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rating'),
        ('posts', '0002_job_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_getter', to='profiles.Profile'),
        ),
    ]
