# Generated by Django 3.0 on 2021-03-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('posts', '0003_auto_20210324_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(null=True, related_name='job_skills', to='profiles.Skill'),
        ),
    ]
