# Generated by Django 3.0 on 2021-04-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210403_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employee',
        ),
    ]
