# Generated by Django 3.0 on 2021-04-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_rating'),
        ('posts', '0004_remove_job_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobappointment',
            old_name='content',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='jobappointment',
            name='receiver',
        ),
        migrations.AddField(
            model_name='job',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_getter', to='profiles.Profile'),
        ),
    ]
