# Generated by Django 3.0 on 2021-03-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('posts', '0004_auto_20210324_0530'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Apply', 'Apply'), ('Approve', 'Approve')], max_length=8)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Apply',
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Job'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
